// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlS-tFFF4Xz5vEoBvlbcCTFgoksKo0JaI',
    appId: '1:729710635843:web:169c368eb099eefe4e1df6',
    messagingSenderId: '729710635843',
    projectId: 'letsride-1ee88',
    authDomain: 'letsride-1ee88.firebaseapp.com',
    storageBucket: 'letsride-1ee88.firebasestorage.app',
    measurementId: 'G-W3HRQ4ZVKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIs5L--XBOiYQByoJgt4M_WU4wxKcxf8',
    appId: '1:729710635843:android:e782cf72190f93014e1df6',
    messagingSenderId: '729710635843',
    projectId: 'letsride-1ee88',
    storageBucket: 'letsride-1ee88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs06wdnVtXE2fEYKmITZr-YkX47ZLNvcY',
    appId: '1:729710635843:ios:97bc2624e44f65bc4e1df6',
    messagingSenderId: '729710635843',
    projectId: 'letsride-1ee88',
    storageBucket: 'letsride-1ee88.firebasestorage.app',
    androidClientId: '729710635843-9j40pia65m21cac0dcj781g5qjf6nluc.apps.googleusercontent.com',
    iosClientId: '729710635843-qqnpe52tbjkadebst6oqktb2m89ksrpb.apps.googleusercontent.com',
    iosBundleId: 'com.mahi.rmmart',
  );

}